package my.testowanie;

public class probatestow extends Exception {
    void foo(){System.out.println("Błąd");}
}
